name: sda_companion
description: All-in-one SDA Offline Application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0            # Local SQLite driver for Bible
  path: ^1.9.0               # File path resolution
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/bible/
    - assets/hymnal/
    - assets/lessons/
